-- Minecraft Church Server: Verification System Database Schema
-- Platform: Paper 1.21.10 with Geyser + Floodgate
-- Created for child-safe access control and verification system

-- Database creation (uncomment if needed)
-- CREATE DATABASE IF NOT EXISTS minecraft_church CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE minecraft_church;

-- ============================================================================
-- Table: verification_codes
-- Purpose: Stores one-time codes generated by NPC for parent verification
-- ============================================================================
CREATE TABLE IF NOT EXISTS verification_codes (
    code VARCHAR(6) PRIMARY KEY COMMENT '6-character one-time code',
    child_name VARCHAR(16) NOT NULL COMMENT 'Minecraft username of child',
    child_uuid VARCHAR(36) NULL COMMENT 'UUID of child player (optional, may be NULL for Bedrock)',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When code was generated',
    expires_at TIMESTAMP NOT NULL COMMENT 'Code expiration time (15 minutes from creation)',
    used_at TIMESTAMP NULL DEFAULT NULL COMMENT 'When code was used (NULL if unused)',
    used_by_email VARCHAR(255) NULL COMMENT 'Email of parent who used the code',
    used_ip VARCHAR(45) NULL COMMENT 'IP address of parent submission (IPv4 or IPv6)',
    INDEX idx_child_name (child_name),
    INDEX idx_expires_at (expires_at),
    INDEX idx_used_at (used_at),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='One-time verification codes generated by NPC';

-- ============================================================================
-- Table: verification_requests
-- Purpose: Stores parent submissions from Wix form awaiting approval
-- ============================================================================
CREATE TABLE IF NOT EXISTS verification_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    child_name VARCHAR(16) NOT NULL COMMENT 'Minecraft username of child',
    adult_name VARCHAR(16) NULL COMMENT 'Minecraft username of adult (optional, only if adult_join=true)',
    code VARCHAR(6) NOT NULL COMMENT 'One-time code used in submission',
    parent_name VARCHAR(255) NOT NULL COMMENT 'Real name of parent/guardian',
    parent_email VARCHAR(255) NOT NULL COMMENT 'Email of parent/guardian',
    consent TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Consent checkbox (1=yes, 0=no)',
    church VARCHAR(255) NULL COMMENT 'Church affiliation (optional)',
    adult_join TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether adult plans to join (1=yes, 0=no)',
    status ENUM('pending', 'approved', 'rejected', 'processed') NOT NULL DEFAULT 'pending' COMMENT 'Request status',
    approved_by VARCHAR(255) NULL COMMENT 'Admin username who approved/rejected',
    approved_at TIMESTAMP NULL DEFAULT NULL COMMENT 'When request was approved/rejected',
    notes TEXT NULL COMMENT 'Admin notes or rejection reason',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When request was submitted',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
    INDEX idx_child_name (child_name),
    INDEX idx_adult_name (adult_name),
    INDEX idx_code (code),
    INDEX idx_status (status),
    INDEX idx_parent_email (parent_email),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (code) REFERENCES verification_codes(code) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Parent verification requests from Wix form';

-- ============================================================================
-- Table: access_grants
-- Purpose: Stores approved access grants that need to be applied via LuckPerms
-- ============================================================================
CREATE TABLE IF NOT EXISTS access_grants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    request_id INT NOT NULL COMMENT 'FK to verification_requests',
    player_name VARCHAR(16) NOT NULL COMMENT 'Minecraft username to grant access to',
    grant_type ENUM('group', 'permission') NOT NULL COMMENT 'Type of grant: group or permission',
    grant_value VARCHAR(255) NOT NULL COMMENT 'Group name (e.g., "child", "adult") or permission node (e.g., "minecraftchurch.volunteer")',
    status ENUM('approved', 'applied', 'failed') NOT NULL DEFAULT 'approved' COMMENT 'Grant status',
    applied_at TIMESTAMP NULL DEFAULT NULL COMMENT 'When grant was successfully applied',
    error TEXT NULL COMMENT 'Error message if application failed',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When grant was created',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
    INDEX idx_request_id (request_id),
    INDEX idx_player_name (player_name),
    INDEX idx_status (status),
    INDEX idx_grant_type (grant_type),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (request_id) REFERENCES verification_requests(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Access grants to be applied via LuckPerms';

-- ============================================================================
-- Table: known_players
-- Purpose: Tracks all players who have joined the server (for audit and platform detection)
-- ============================================================================
CREATE TABLE IF NOT EXISTS known_players (
    player_name VARCHAR(16) PRIMARY KEY COMMENT 'Minecraft username',
    uuid VARCHAR(36) NULL COMMENT 'Player UUID (may be NULL for Bedrock players)',
    platform ENUM('java', 'bedrock', 'unknown') NOT NULL DEFAULT 'unknown' COMMENT 'Platform type',
    first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'First time player joined',
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last time player was seen',
    INDEX idx_uuid (uuid),
    INDEX idx_platform (platform),
    INDEX idx_last_seen_at (last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Registry of all players who have joined the server';

-- ============================================================================
-- Optional: Audit log table for tracking all approval actions
-- ============================================================================
CREATE TABLE IF NOT EXISTS audit_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    action_type VARCHAR(50) NOT NULL COMMENT 'Type of action (approve, reject, grant_applied, etc.)',
    admin_user VARCHAR(255) NULL COMMENT 'Admin who performed action',
    target_player VARCHAR(16) NULL COMMENT 'Player affected by action',
    request_id INT NULL COMMENT 'Related verification request ID',
    grant_id INT NULL COMMENT 'Related access grant ID',
    details JSON NULL COMMENT 'Additional action details in JSON format',
    ip_address VARCHAR(45) NULL COMMENT 'IP address of admin/user',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When action occurred',
    INDEX idx_action_type (action_type),
    INDEX idx_admin_user (admin_user),
    INDEX idx_target_player (target_player),
    INDEX idx_request_id (request_id),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (request_id) REFERENCES verification_requests(id) ON DELETE SET NULL,
    FOREIGN KEY (grant_id) REFERENCES access_grants(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Audit log for all administrative actions';
